const thoughts = [
    {
      "post": "Just enjoying a quiet evening at home. 😊",
      "user": "John Doe",
      "likes": [],
    },
    {
      "post": "Excited about the weekend plans! 🎉",
      "user": "Alice Johnson",
      "likes": [],
    },
    {
      "post": "Coding session in progress. 💻 #Programming",
      "user": "David Smith",
      "likes": [],
    },
    {
      "post": "Chilling with a good book and some tea. 📚☕",
      "user": "Emma Davis",
      "likes": [],
    },
    {
      "post": "Exploring new places today! 🌍 #AdventureTime",
      "user": "Michael Turner",
      "likes": [],
    },
    {
      "post": "Music is my therapy. 🎶 What's your favorite song?",
      "user": "Sophia White",
      "likes": [],
    },
    {
      "post": "Gaming night with friends! 🎮 #GamersUnite",
      "user": "Daniel Brown",
      "likes": [],
    },
    {
      "post": "Cooking up a storm in the kitchen tonight. 🍲 #Foodie",
      "user": "Olivia Miller",
      "likes": [],
    },
    {
      "post": "Reflecting on the day's achievements. 💪 #Goals",
      "user": "Matthew Carter",
      "likes": [],
    },
    {
      "post": "Sunset walks are my favorite way to unwind. 🌅 #NatureLover",
      "user": "Emily Young",
      "likes": [],
    },
    {
      "post": "Movie night at home. Any recommendations? 🍿🎬",
      "user": "Alice Johnson",
      "likes": [],
    },
    {
      "post": "Working on a new art project. 🎨 #Creativity",
      "user": "Michael Turner",
      "likes": [],
    },
    {
      "post": "Feeling grateful for the little things. 🌺 #Gratitude",
      "user": "Sophia White",
      "likes": [],
    },
    {
      "post": "Saturday vibes! What's everyone up to? 😄",
      "user": "Sophia White",
      "likes": [],
    },
    {
      "post": "Exciting news coming soon! Stay tuned. 🚀 #Teaser",
      "user": "Emily Young",
      "likes": [],
    },
    {
      "post": "Homemade cookies for the win! 🍪 #Baking",
      "user": "Matthew Carter",
      "likes": [],
    },
    {
      "post": "Staying active with a morning jog. 🏃‍♂️ #FitnessJourney",
      "user": "Emily Young",
      "likes": [],
    },
    {
      "post": "Lost in a good book. Any book recommendations? 📖",
      "user": "David Smith",
      "likes": [],
    },
    {
      "post": "Artistic vibes today. ✨ #ArtIsLife",
      "user": "Alice Johnson",
      "likes": [],
    },
    {
      "post": "Positive vibes only! Spread kindness. ❤️ #PositiveThinking",
      "user": "John Doe",
      "likes": [],
    },
    {
      "post": "Sunday brunch with friends. Good times! 🥞🍹",
      "user": "John Doe",
      "likes": [],
    },
    {
      "post": "Nature walk and fresh air. Perfect Sunday afternoon. 🌳☀️",
      "user": "Alice Johnson",
      "likes": [],
    },
    {
      "post": "Quiet night in with a movie marathon. 🍿🎥 #CozyEvening",
      "user": "David Smith",
      "likes": [],
    },
    {
      "post": "Productive day at work. Time to unwind. 🌙 #WorkLifeBalance",
      "user": "Emma Davis",
      "likes": [],
    }
];  

const users = [
    {
      "full_name": "John Doe",
      "first": "John",
      "last": "Doe",
      "email": "john.doe@example.com",
      "password": "P@ssw0rd",
      "friends": [],
      "thoughts": [],
      "likes": [],
    },
    {
      "full_name": "Alice Johnson",
      "first": "Alice",
      "last": "Johnson",
      "email": "alice.johnson@example.com",
      "password": "SecurePwd1",
      "friends": [],
      "thoughts": [],
      "likes": [],
    },
    {
      "full_name": "David Smith",
      "first": "David",
      "last": "Smith",
      "email": "david.smith@example.com",
      "password": "Strong123",
      "friends": [],
      "thoughts": [],
      "likes": [],
    },
    {
      "full_name": "Emma Davis",
      "first": "Emma",
      "last": "Davis",
      "email": "emma.davis@example.com",
      "password": "Passw0rd!",
      "friends": [],
      "thoughts": [],
      "likes": [],
    },
    {
      "full_name": "Michael Turner",
      "first": "Michael",
      "last": "Turner",
      "email": "michael.turner@example.com",
      "password": "Secret123",
      "friends": [],
      "thoughts": [],
      "likes": [],
    },
    {
      "full_name": "Sophia White",
      "first": "Sophia",
      "last": "White",
      "email": "sophia.white@example.com",
      "password": "StrongPwd",
      "friends": [],
      "thoughts": [],
      "likes": [],
    },
    {
      "full_name": "Daniel Brown",
      "first": "Daniel",
      "last": "Brown",
      "email": "daniel.brown@example.com",
      "password": "Brownie45",
      "friends": [],
      "thoughts": [],
      "likes": [],
    },
    {
      "full_name": "Olivia Miller",
      "first": "Olivia",
      "last": "Miller",
      "email": "olivia.miller@example.com",
      "password": "MillerPass",
      "friends": [],
      "thoughts": [],
      "likes": [],
    },
    {
      "full_name": "Matthew Carter",
      "first": "Matthew",
      "last": "Carter",
      "email": "matthew.carter@example.com",
      "password": "Carter123",
      "friends": [],
      "thoughts": [],
      "likes": [],
    },
    {
      "full_name": "Emily Young",
      "first": "Emily",
      "last": "Young",
      "email": "emily.young@example.com",
      "password": "YoungPwd!",
      "friends": [],
      "thoughts": [],
      "likes": [],
    }
];


module.exports = { thoughts, users };